#!/bin/sh
### BEGIN INIT INFO
# Provides:          OpenMediaKit-Server-Metadata
# Required-Start:    $network $named $remote_fs $syslog
# Required-Stop:     $network $named $remote_fs $syslog
# Should-Start:      OpenMediaKit-Server-Metadata
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: OpenMediaKit Server Metadata computing service
# Description:       The OpenMediaKit Server service is providing
#                    its subscribed users with a Video Transcoding service. 
#                    This daemon do the Metadata finding on the subscribers videos
### END INIT INFO

OMKROOT=/var/www/omk
CHOWN=www-data

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=$OMKROOT/modules/api/scripts/metadata.daemon.php
DAEMON_OPTS=""
NAME="omk-metadata"
DESC="OpenMediaKit Server METADATA Computing Service"
PIDFILE="/var/run/${NAME}.pid"

test -x $DAEMON || exit 0

. /lib/lsb/init-functions

case "$1" in
    start)
	log_begin_msg "Starting $DESC"
	start-stop-daemon --start --quiet --pidfile $PIDFILE \
	    --background --make-pidfile --chuid $CHOWN \
	    --startas $DAEMON -- $DAEMON_OPTS
	log_end_msg $?
	;;
    stop)
	log_begin_msg "Stopping $DESC"
	start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE --chuid $CHOWN
	log_end_msg $?
	;;
    status)
	status_of_proc -p "${PIDFILE}" "${DAEMON}" "${NAME}"
	;;
    reload|restart|force-reload)
	log_begin_msg "Restarting $DESC"
	$0 stop
	sleep 1
	$0 start
	log_end_msg $?
	;;
  *)
	echo "Usage: $0 {start|stop|status|restart|force-reload|reload}" >&2
	exit 1
	;;
esac
