<?php 
/*
 * These are the standard settings of OpenMediaKit
 * See http://www.open-mediakit.org/ for more information
 * WARNING: this file is automatically generated from ../scripts/update_settings.php !
 */
    global $settings;

$settings=array(
   array(
          "id" => "1",
          "type" => "video",
          "slug" => "video_240p_flv",
          "name" => "Video at very low definition and flash sorenson format",
          "technical" => "flv container, sorenson video at 280kb/s, mp3 audio at 64kb/s and 22KHz, 426x240 pixels on 16:9, 25fps",
          "extension" => "flv",
          "recommend" => "1",
        ),

   array(
          "id" => "2",
          "type" => "video",
          "slug" => "video_360p_flv",
          "name" => "Video at low definition and flash sorenson format",
          "technical" => "flv container, sorenson video at 440kb/s, mp3 audio at 128kb/s and 44KHz, 640x360 pixels on 16:9, 25fps",
          "extension" => "flv",
          "recommend" => "1",
        ),

   array(
          "id" => "3",
          "type" => "video",
          "slug" => "video_480p_flv",
          "name" => "Video at low definition and flash sorenson format",
          "technical" => "flv container, sorenson video at 440kb/s, mp3 audio at 128kb/s and 44KHz, 854x480 pixels on 16:9, 25fps",
          "extension" => "flv",
          "recommend" => "0",
        ),

   array(
          "id" => "11",
          "type" => "video",
          "slug" => "video_240p_mp4",
          "name" => "Video at very low definition and portable mp4 format",
          "technical" => "mp4 container, h264 video at 280kb/s, aac audio at 64kb/s and 22KHz, 426x240 pixels on 16:9, 25fps",
          "extension" => "mp4",
          "recommend" => "0",
        ),

   array(
          "id" => "12",
          "type" => "video",
          "slug" => "video_360p_mp4",
          "name" => "Video at low definition and portable mp4 format",
          "technical" => "mp4 container, h264 video at 440kb/s, aac audio at 128kb/s and 44KHz, 640x360 pixels on 16:9, 25fps",
          "extension" => "mp4",
          "recommend" => "0",
        ),

   array(
          "id" => "13",
          "type" => "video",
          "slug" => "video_480p_mp4",
          "name" => "Video at standard definition and portable mp4 format",
          "technical" => "mp4 container, h264 video at 680kb/s, aac audio at 128kb/s and 44KHz, 854x480 pixels on 16:9, 30fps",
          "extension" => "mp4",
          "recommend" => "1",
        ),

   array(
          "id" => "14",
          "type" => "video",
          "slug" => "video_720p_mp4",
          "name" => "Video at high definition and portable mp4 format",
          "technical" => "mp4 container, h264 video at 1650kb/s, aac audio at 192kb/s and 44KHz, 1280x720 pixels on 16:9, 30fps",
          "extension" => "mp4",
          "recommend" => "1",
        ),

   array(
          "id" => "15",
          "type" => "video",
          "slug" => "video_1080p_mp4",
          "name" => "Video at full-hd definition and portable mp4 format",
          "technical" => "mp4 container, h264 video at 4000kb/s, aac audio at 192kb/s and 44KHz, 1920x1080 pixels on 16:9, 30fps",
          "extension" => "mp4",
          "recommend" => "1",
        ),

   array(
          "id" => "21",
          "type" => "video",
          "slug" => "video_240p_webm",
          "name" => "Video at very low definition and webm opensource format",
          "technical" => "webm container, vp8 video at 280kb/s, vorbis audio at 64kb/s and 22KHz, 426x240 pixels on 16:9, 25fps",
          "extension" => "webm",
          "recommend" => "0",
        ),

   array(
          "id" => "22",
          "type" => "video",
          "slug" => "video_360p_webm",
          "name" => "Video at low definition and webm opensource format",
          "technical" => "webm container, vp8 video at 440kb/s, vorbis audio at 128kb/s and 44KHz, 640x360 pixels on 16:9, 25fps",
          "extension" => "webm",
          "recommend" => "0",
        ),

   array(
          "id" => "23",
          "type" => "video",
          "slug" => "video_480p_webm",
          "name" => "Video at standard definition webm opensource format",
          "technical" => "webm container, vp8 video at 680kb/s, vorbis audio at 128kb/s and 44KHz, 854x480 pixels on 16:9, 30fps",
          "extension" => "webm",
          "recommend" => "1",
        ),

   array(
          "id" => "24",
          "type" => "video",
          "slug" => "video_720p_webm",
          "name" => "Video at high definition and webm opensource format",
          "technical" => "webm container, vp8 video at 1650kb/s, vorbis audio at 192kb/s and 44KHz, 1280x720 pixels on 16:9, 30fps",
          "extension" => "webm",
          "recommend" => "1",
        ),

   array(
          "id" => "25",
          "type" => "video",
          "slug" => "video_1080p_webm",
          "name" => "Video at full-hd definition and webm opensource format",
          "technical" => "webm container, vp8 video at 4000kb/s, vorbis audio at 192kb/s and 44KHz, 1920x1080 pixels on 16:9, 30fps",
          "extension" => "webm",
          "recommend" => "1",
        ),

   array(
          "id" => "31",
          "type" => "video",
          "slug" => "video_240p_mpeg",
          "name" => "Video at very low definition and mpeg broadcast format",
          "technical" => "mpeg container, mpeg2 video at 280kb/s, mpeg2 audio at 64kb/s and 22KHz, 426x240 pixels on 16:9, 25fps",
          "extension" => "mpg",
          "recommend" => "0",
        ),

   array(
          "id" => "32",
          "type" => "video",
          "slug" => "video_360p_mpeg",
          "name" => "Video at low definition and mpeg broadcast format",
          "technical" => "mpeg container, mpeg2 video at 440kb/s, mpeg2 audio at 128kb/s and 44KHz, 640x360 pixels on 16:9, 25fps",
          "extension" => "mpg",
          "recommend" => "0",
        ),

   array(
          "id" => "33",
          "type" => "video",
          "slug" => "video_480p_mpeg",
          "name" => "Video at standard definition mpeg broadcast format",
          "technical" => "mpeg container, mpeg2 video at 680kb/s, mpeg2 audio at 128kb/s and 44KHz, 854x480 pixels on 16:9, 30fps",
          "extension" => "mpg",
          "recommend" => "0",
        ),

   array(
          "id" => "34",
          "type" => "video",
          "slug" => "video_720p_mpeg",
          "name" => "Video at high definition and mpeg broadcast format",
          "technical" => "mpeg container, mpeg2 video at 1650kb/s, mpeg2 audio at 192kb/s and 44KHz, 1280x720 pixels on 16:9, 30fps",
          "extension" => "mpg",
          "recommend" => "0",
        ),

   array(
          "id" => "35",
          "type" => "video",
          "slug" => "video_1080p_mpeg",
          "name" => "Video at full-hd definition and mpeg broadcast format",
          "technical" => "mpeg container, mpeg2 video at 4000kb/s, mpeg2 audio at 192kb/s and 44KHz, 1920x1080 pixels on 16:9, 30fps",
          "extension" => "mpg",
          "recommend" => "0",
        ),

   array(
          "id" => "51",
          "type" => "audio",
          "slug" => "audio_64k_mp3",
          "name" => "Audio track only, with low quality",
          "technical" => "mp3 container, mp3 audio track at 64Kb/s and 22KHz, stereo",
          "extension" => "mp3",
          "recommend" => "0",
        ),

   array(
          "id" => "52",
          "type" => "audio",
          "slug" => "audio_128k_mp3",
          "name" => "Audio track only, with standard quality",
          "technical" => "mp3 container, mp3 audio track at 128Kb/s and 44KHz, stereo",
          "extension" => "mp3",
          "recommend" => "1",
        ),

   array(
          "id" => "53",
          "type" => "audio",
          "slug" => "audio_v0_mp3",
          "name" => "Audio track only, with highest mp3 quality",
          "technical" => "mp3 container, mp3 audio track at V0 quality and 44KHz, stereo",
          "extension" => "mp3",
          "recommend" => "1",
        ),

   array(
          "id" => "61",
          "type" => "audio",
          "slug" => "audio_64k_vorbis",
          "name" => "Audio track only, with low quality and opensource vorbis codec",
          "technical" => "ogg container, vorbis audio track at 64Kb/s and 22KHz, stereo",
          "extension" => "ogg",
          "recommend" => "0",
        ),

   array(
          "id" => "62",
          "type" => "audio",
          "slug" => "audio_128k_vorbis",
          "name" => "Audio track only, with standard quality and opensource vorbis codec",
          "technical" => "ogg container, vorbis audio track at 128Kb/s and 44KHz, stereo",
          "extension" => "ogg",
          "recommend" => "0",
        ),

   array(
          "id" => "63",
          "type" => "audio",
          "slug" => "audio_v0_vorbis",
          "name" => "Audio track only, with highest quality and opensource vorbis codec",
          "technical" => "ogg container, vorbis audio track at V0 quality and 44KHz, stereo",
          "extension" => "ogg",
          "recommend" => "0",
        ),

   array(
          "id" => "71",
          "type" => "audio",
          "slug" => "audio_64k_aac",
          "name" => "Audio track only, with low quality and aac codec",
          "technical" => "mp4 container, aac audio track at 64kb/s quality and 22KHz, stereo",
          "extension" => "m4a",
          "recommend" => "0",
        ),

   array(
          "id" => "72",
          "type" => "audio",
          "slug" => "audio_128k_aac",
          "name" => "Audio track only, with standard quality and aac codec",
          "technical" => "mp4 container, aac audio track at 128kb/s quality and 44KHz, stereo",
          "extension" => "m4a",
          "recommend" => "0",
        ),

   array(
          "id" => "73",
          "type" => "audio",
          "slug" => "audio_192k_aac",
          "name" => "Audio track only, with highest quality and aac codec",
          "technical" => "mp4 container, aac audio track at 192kb/s quality and 44KHz, stereo",
          "extension" => "m4a",
          "recommend" => "0",
        ),

   array(
          "id" => "101",
          "type" => "thumbnails",
          "slug" => "100_240p_thumbs_jpg",
          "name" => "100 thumbnails at 240p as jpg files",
          "technical" => "100 jpg at 80% quality, no more than 1 every 10 seconds, size 426x240",
          "extension" => "jpg",
          "recommend" => "0",
        ),

   array(
          "id" => "102",
          "type" => "thumbnails",
          "slug" => "100_360p_thumbs_jpg",
          "name" => "100 thumbnails at 360p as jpg files",
          "technical" => "100 jpg at 80% quality, no more than 1 every 10 seconds, size 640x360",
          "extension" => "jpg",
          "recommend" => "0",
        ),

   array(
          "id" => "103",
          "type" => "thumbnails",
          "slug" => "100_480p_thumbs_jpg",
          "name" => "100 thumbnails at 480p as jpg files",
          "technical" => "100 jpg at 80% quality, no more than 1 every 10 seconds, size 854x480",
          "extension" => "jpg",
          "recommend" => "1",
        ),

   array(
          "id" => "104",
          "type" => "thumbnails",
          "slug" => "100_720p_thumbs_jpg",
          "name" => "100 thumbnails at 720p as jpg files",
          "technical" => "100 jpg at 80% quality, no more than 1 every 10 seconds, size 1280x720",
          "extension" => "jpg",
          "recommend" => "0",
        ),

   array(
          "id" => "105",
          "type" => "thumbnails",
          "slug" => "100_1080p_thumbs_jpg",
          "name" => "100 thumbnails at 1080p as jpg files",
          "technical" => "100 jpg at 80% quality, no more than 1 every 10 seconds, size 1920x1080",
          "extension" => "jpg",
          "recommend" => "0",
        ),

   array(
          "id" => "110",
          "type" => "thumbnails",
          "slug" => "100_small_thumbs_jpg",
          "name" => "100 small thumbnails as jpg files",
          "technical" => "100 jpg at 80% quality, no more than 1 every 2 seconds, size 100x60 (width guaranteed)",
          "extension" => "jpg",
          "recommend" => "1",
        ),

   array(
          "id" => "111",
          "type" => "thumbnails",
          "slug" => "100_medium_thumbs_jpg",
          "name" => "100 medium thumbnails as jpg files",
          "technical" => "100 jpg at 80% quality, no more than 1 every 2 seconds, size 200x120 (width guaranteed)",
          "extension" => "jpg",
          "recommend" => "0",
        ),


 );

?>
